package br.pucsp.locar.entity;
// Generated 15/05/2016 13:10:26 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Avaliacaolocacao generated by hbm2java
 */
@Entity
@Table(name = "avaliacaolocacao", catalog = "schema_locar")
public class Avaliacaolocacao implements java.io.Serializable {

	private AvaliacaolocacaoId id;
	private Avaliacao avaliacao;
	private Locacao locacao;
	private Login login;

	public Avaliacaolocacao() {
	}

	public Avaliacaolocacao(AvaliacaolocacaoId id, Avaliacao avaliacao, Locacao locacao, Login login) {
		this.id = id;
		this.avaliacao = avaliacao;
		this.locacao = locacao;
		this.login = login;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idAvaliacao", column = @Column(name = "idAvaliacao", nullable = false)),
			@AttributeOverride(name = "idLocacao", column = @Column(name = "idLocacao", nullable = false)),
			@AttributeOverride(name = "idLogin", column = @Column(name = "idLogin", nullable = false, length = 15)) })
	public AvaliacaolocacaoId getId() {
		return this.id;
	}

	public void setId(AvaliacaolocacaoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idAvaliacao", nullable = false, insertable = false, updatable = false)
	public Avaliacao getAvaliacao() {
		return this.avaliacao;
	}

	public void setAvaliacao(Avaliacao avaliacao) {
		this.avaliacao = avaliacao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idLocacao", nullable = false, insertable = false, updatable = false)
	public Locacao getLocacao() {
		return this.locacao;
	}

	public void setLocacao(Locacao locacao) {
		this.locacao = locacao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idLogin", nullable = false, insertable = false, updatable = false)
	public Login getLogin() {
		return this.login;
	}

	public void setLogin(Login login) {
		this.login = login;
	}

}
