package br.pucsp.locar.entity;
// Generated 28/05/2016 00:02:55 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cidade generated by hbm2java
 */
@Entity
@Table(name = "cidade", catalog = "schema_locar")
public class Cidade implements java.io.Serializable {

	private Integer codCid;
	private Estado estado;
	private String nome;
	private Set<Endereco> enderecos = new HashSet<Endereco>(0);

	public Cidade() {
	}

	public Cidade(Estado estado, String nome) {
		this.estado = estado;
		this.nome = nome;
	}

	public Cidade(Estado estado, String nome, Set<Endereco> enderecos) {
		this.estado = estado;
		this.nome = nome;
		this.enderecos = enderecos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "codCid", unique = true, nullable = false)
	public Integer getCodCid() {
		return this.codCid;
	}

	public void setCodCid(Integer codCid) {
		this.codCid = codCid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sigla", nullable = false)
	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	@Column(name = "nome", nullable = false, length = 100)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cidade")
	public Set<Endereco> getEnderecos() {
		return this.enderecos;
	}

	public void setEnderecos(Set<Endereco> enderecos) {
		this.enderecos = enderecos;
	}

}
