package br.pucsp.locar.entity;
// Generated 15/05/2016 13:10:26 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Disponibilidadeveiculo generated by hbm2java
 */
@Entity
@Table(name = "disponibilidadeveiculo", catalog = "schema_locar")
public class Disponibilidadeveiculo implements java.io.Serializable {

	private Integer idDisponibilidade;
	private Endereco endereco;
	private Localizacao localizacao;
	private Veiculo veiculo;
	private Date dtinicio;
	private Date dtfinal;

	public Disponibilidadeveiculo() {
	}

	public Disponibilidadeveiculo(Endereco endereco, Localizacao localizacao, Veiculo veiculo, Date dtinicio,
			Date dtfinal) {
		this.endereco = endereco;
		this.localizacao = localizacao;
		this.veiculo = veiculo;
		this.dtinicio = dtinicio;
		this.dtfinal = dtfinal;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idDisponibilidade", unique = true, nullable = false)
	public Integer getIdDisponibilidade() {
		return this.idDisponibilidade;
	}

	public void setIdDisponibilidade(Integer idDisponibilidade) {
		this.idDisponibilidade = idDisponibilidade;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codEnd", nullable = false)
	public Endereco getEndereco() {
		return this.endereco;
	}

	public void setEndereco(Endereco endereco) {
		this.endereco = endereco;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idLocalizacao", nullable = false)
	public Localizacao getLocalizacao() {
		return this.localizacao;
	}

	public void setLocalizacao(Localizacao localizacao) {
		this.localizacao = localizacao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "placa", nullable = false)
	public Veiculo getVeiculo() {
		return this.veiculo;
	}

	public void setVeiculo(Veiculo veiculo) {
		this.veiculo = veiculo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dtinicio", nullable = false, length = 19)
	public Date getDtinicio() {
		return this.dtinicio;
	}

	public void setDtinicio(Date dtinicio) {
		this.dtinicio = dtinicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dtfinal", nullable = false, length = 19)
	public Date getDtfinal() {
		return this.dtfinal;
	}

	public void setDtfinal(Date dtfinal) {
		this.dtfinal = dtfinal;
	}

}
