package br.pucsp.locar.entity;
// Generated 15/05/2016 13:10:26 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Endereco generated by hbm2java
 */
@Entity
@Table(name = "endereco", catalog = "schema_locar")
public class Endereco implements java.io.Serializable {

	private Integer codEnd;
	private Cidade cidade;
	private Tipoendereco tipoendereco;
	private String logradouro;
	private int numero;
	private String bairro;
	private Set<Disponibilidadeveiculo> disponibilidadeveiculos = new HashSet<Disponibilidadeveiculo>(0);
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Endereco() {
	}

	public Endereco(Cidade cidade, Tipoendereco tipoendereco, String logradouro, int numero, String bairro) {
		this.cidade = cidade;
		this.tipoendereco = tipoendereco;
		this.logradouro = logradouro;
		this.numero = numero;
		this.bairro = bairro;
	}

	public Endereco(Cidade cidade, Tipoendereco tipoendereco, String logradouro, int numero, String bairro,
			Set<Disponibilidadeveiculo> disponibilidadeveiculos, Set<Usuario> usuarios) {
		this.cidade = cidade;
		this.tipoendereco = tipoendereco;
		this.logradouro = logradouro;
		this.numero = numero;
		this.bairro = bairro;
		this.disponibilidadeveiculos = disponibilidadeveiculos;
		this.usuarios = usuarios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "codEnd", unique = true, nullable = false)
	public Integer getCodEnd() {
		return this.codEnd;
	}

	public void setCodEnd(Integer codEnd) {
		this.codEnd = codEnd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codCid", nullable = false)
	public Cidade getCidade() {
		return this.cidade;
	}

	public void setCidade(Cidade cidade) {
		this.cidade = cidade;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codTipoEnd", nullable = false)
	public Tipoendereco getTipoendereco() {
		return this.tipoendereco;
	}

	public void setTipoendereco(Tipoendereco tipoendereco) {
		this.tipoendereco = tipoendereco;
	}

	@Column(name = "logradouro", nullable = false, length = 60)
	public String getLogradouro() {
		return this.logradouro;
	}

	public void setLogradouro(String logradouro) {
		this.logradouro = logradouro;
	}

	@Column(name = "numero", nullable = false)
	public int getNumero() {
		return this.numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

	@Column(name = "bairro", nullable = false, length = 60)
	public String getBairro() {
		return this.bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "endereco")
	public Set<Disponibilidadeveiculo> getDisponibilidadeveiculos() {
		return this.disponibilidadeveiculos;
	}

	public void setDisponibilidadeveiculos(Set<Disponibilidadeveiculo> disponibilidadeveiculos) {
		this.disponibilidadeveiculos = disponibilidadeveiculos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "endereco")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
