package br.pucsp.locar.entity;
// Generated 15/05/2016 13:10:26 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Estacionamento generated by hbm2java
 */
@Entity
@Table(name = "estacionamento", catalog = "schema_locar", uniqueConstraints = @UniqueConstraint(columnNames = "cnpj"))
public class Estacionamento implements java.io.Serializable {

	private String idLogin;
	private Login login;
	private String nomeEstacionamento;
	private String nomeProprietario;
	private long cnpj;
	private int numFuncionarios;
	private int numVagas;
	private int codEnd;

	public Estacionamento() {
	}

	public Estacionamento(Login login, String nomeEstacionamento, String nomeProprietario, long cnpj,
			int numFuncionarios, int numVagas, int codEnd) {
		this.login = login;
		this.nomeEstacionamento = nomeEstacionamento;
		this.nomeProprietario = nomeProprietario;
		this.cnpj = cnpj;
		this.numFuncionarios = numFuncionarios;
		this.numVagas = numVagas;
		this.codEnd = codEnd;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "login"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "idLogin", unique = true, nullable = false, length = 15)
	public String getIdLogin() {
		return this.idLogin;
	}

	public void setIdLogin(String idLogin) {
		this.idLogin = idLogin;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Login getLogin() {
		return this.login;
	}

	public void setLogin(Login login) {
		this.login = login;
	}

	@Column(name = "nomeEstacionamento", nullable = false, length = 100)
	public String getNomeEstacionamento() {
		return this.nomeEstacionamento;
	}

	public void setNomeEstacionamento(String nomeEstacionamento) {
		this.nomeEstacionamento = nomeEstacionamento;
	}

	@Column(name = "nomeProprietario", nullable = false, length = 100)
	public String getNomeProprietario() {
		return this.nomeProprietario;
	}

	public void setNomeProprietario(String nomeProprietario) {
		this.nomeProprietario = nomeProprietario;
	}

	@Column(name = "cnpj", unique = true, nullable = false, precision = 14, scale = 0)
	public long getCnpj() {
		return this.cnpj;
	}

	public void setCnpj(long cnpj) {
		this.cnpj = cnpj;
	}

	@Column(name = "numFuncionarios", nullable = false)
	public int getNumFuncionarios() {
		return this.numFuncionarios;
	}

	public void setNumFuncionarios(int numFuncionarios) {
		this.numFuncionarios = numFuncionarios;
	}

	@Column(name = "numVagas", nullable = false)
	public int getNumVagas() {
		return this.numVagas;
	}

	public void setNumVagas(int numVagas) {
		this.numVagas = numVagas;
	}

	@Column(name = "codEnd", nullable = false)
	public int getCodEnd() {
		return this.codEnd;
	}

	public void setCodEnd(int codEnd) {
		this.codEnd = codEnd;
	}

}
