package br.pucsp.locar.entity;
// Generated 15/05/2016 13:10:26 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Localizacao generated by hbm2java
 */
@Entity
@Table(name = "localizacao", catalog = "schema_locar")
public class Localizacao implements java.io.Serializable {

	private int idLocalizacao;
	private Date dtinclusao;
	private String latitude;
	private String longitude;
	private Set<Disponibilidadeveiculo> disponibilidadeveiculos = new HashSet<Disponibilidadeveiculo>(0);

	public Localizacao() {
	}

	public Localizacao(int idLocalizacao, Date dtinclusao, String latitude, String longitude) {
		this.idLocalizacao = idLocalizacao;
		this.dtinclusao = dtinclusao;
		this.latitude = latitude;
		this.longitude = longitude;
	}

	public Localizacao(int idLocalizacao, Date dtinclusao, String latitude, String longitude,
			Set<Disponibilidadeveiculo> disponibilidadeveiculos) {
		this.idLocalizacao = idLocalizacao;
		this.dtinclusao = dtinclusao;
		this.latitude = latitude;
		this.longitude = longitude;
		this.disponibilidadeveiculos = disponibilidadeveiculos;
	}

	@Id

	@Column(name = "idLocalizacao", unique = true, nullable = false)
	public int getIdLocalizacao() {
		return this.idLocalizacao;
	}

	public void setIdLocalizacao(int idLocalizacao) {
		this.idLocalizacao = idLocalizacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dtinclusao", nullable = false, length = 19)
	public Date getDtinclusao() {
		return this.dtinclusao;
	}

	public void setDtinclusao(Date dtinclusao) {
		this.dtinclusao = dtinclusao;
	}

	@Column(name = "latitude", nullable = false, length = 20)
	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", nullable = false, length = 20)
	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "localizacao")
	public Set<Disponibilidadeveiculo> getDisponibilidadeveiculos() {
		return this.disponibilidadeveiculos;
	}

	public void setDisponibilidadeveiculos(Set<Disponibilidadeveiculo> disponibilidadeveiculos) {
		this.disponibilidadeveiculos = disponibilidadeveiculos;
	}

}
