package br.pucsp.locar.entity;
// Generated 28/05/2016 00:02:55 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Questaoavaliacao generated by hbm2java
 */
@Entity
@Table(name = "questaoavaliacao", catalog = "schema_locar")
public class Questaoavaliacao implements java.io.Serializable {

	private int idQuestao;
	private Tipoperfil tipoperfil;
	private String questao;
	private Set<Avaliacao> avaliacaos = new HashSet<Avaliacao>(0);

	public Questaoavaliacao() {
	}

	public Questaoavaliacao(int idQuestao, Tipoperfil tipoperfil, String questao) {
		this.idQuestao = idQuestao;
		this.tipoperfil = tipoperfil;
		this.questao = questao;
	}

	public Questaoavaliacao(int idQuestao, Tipoperfil tipoperfil, String questao, Set<Avaliacao> avaliacaos) {
		this.idQuestao = idQuestao;
		this.tipoperfil = tipoperfil;
		this.questao = questao;
		this.avaliacaos = avaliacaos;
	}

	@Id

	@Column(name = "idQuestao", unique = true, nullable = false)
	public int getIdQuestao() {
		return this.idQuestao;
	}

	public void setIdQuestao(int idQuestao) {
		this.idQuestao = idQuestao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codPerfil", nullable = false)
	public Tipoperfil getTipoperfil() {
		return this.tipoperfil;
	}

	public void setTipoperfil(Tipoperfil tipoperfil) {
		this.tipoperfil = tipoperfil;
	}

	@Column(name = "questao", nullable = false, length = 150)
	public String getQuestao() {
		return this.questao;
	}

	public void setQuestao(String questao) {
		this.questao = questao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "questaoavaliacao")
	public Set<Avaliacao> getAvaliacaos() {
		return this.avaliacaos;
	}

	public void setAvaliacaos(Set<Avaliacao> avaliacaos) {
		this.avaliacaos = avaliacaos;
	}

}
