package br.pucsp.locar.entity;
// Generated 15/05/2016 13:10:26 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Statusreserva generated by hbm2java
 */
@Entity
@Table(name = "statusreserva", catalog = "schema_locar")
public class Statusreserva implements java.io.Serializable {

	private char status;
	private String descricao;
	private Set<Reserva> reservas = new HashSet<Reserva>(0);

	public Statusreserva() {
	}

	public Statusreserva(char status, String descricao) {
		this.status = status;
		this.descricao = descricao;
	}

	public Statusreserva(char status, String descricao, Set<Reserva> reservas) {
		this.status = status;
		this.descricao = descricao;
		this.reservas = reservas;
	}

	@Id

	@Column(name = "status", unique = true, nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "descricao", nullable = false, length = 15)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statusreserva")
	public Set<Reserva> getReservas() {
		return this.reservas;
	}

	public void setReservas(Set<Reserva> reservas) {
		this.reservas = reservas;
	}

}
