package br.pucsp.locar.entity;
// Generated 28/05/2016 00:02:55 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Telefone generated by hbm2java
 */
@Entity
@Table(name = "telefone", catalog = "schema_locar")
public class Telefone implements java.io.Serializable {

	private Integer codTel;
	private Login login;
	private Tipotelefone tipotelefone;
	private int ddd;
	private int numero;

	public Telefone() {
	}

	public Telefone(Login login, Tipotelefone tipotelefone, int ddd, int numero) {
		this.login = login;
		this.tipotelefone = tipotelefone;
		this.ddd = ddd;
		this.numero = numero;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "codTel", unique = true, nullable = false)
	public Integer getCodTel() {
		return this.codTel;
	}

	public void setCodTel(Integer codTel) {
		this.codTel = codTel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idLogin", nullable = false)
	public Login getLogin() {
		return this.login;
	}

	public void setLogin(Login login) {
		this.login = login;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codTipoTel", nullable = false)
	public Tipotelefone getTipotelefone() {
		return this.tipotelefone;
	}

	public void setTipotelefone(Tipotelefone tipotelefone) {
		this.tipotelefone = tipotelefone;
	}

	@Column(name = "ddd", nullable = false)
	public int getDdd() {
		return this.ddd;
	}

	public void setDdd(int ddd) {
		this.ddd = ddd;
	}

	@Column(name = "numero", nullable = false)
	public int getNumero() {
		return this.numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

}
