package br.pucsp.locar.entity;
// Generated 15/05/2016 13:10:26 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipoperfil generated by hbm2java
 */
@Entity
@Table(name = "tipoperfil", catalog = "schema_locar")
public class Tipoperfil implements java.io.Serializable {

	private int codPerfil;
	private String descricao;
	private Set<Loginperfil> loginperfils = new HashSet<Loginperfil>(0);
	private Set<Questaoavaliacao> questaoavaliacaos = new HashSet<Questaoavaliacao>(0);

	public Tipoperfil() {
	}

	public Tipoperfil(int codPerfil, String descricao) {
		this.codPerfil = codPerfil;
		this.descricao = descricao;
	}

	public Tipoperfil(int codPerfil, String descricao, Set<Loginperfil> loginperfils,
			Set<Questaoavaliacao> questaoavaliacaos) {
		this.codPerfil = codPerfil;
		this.descricao = descricao;
		this.loginperfils = loginperfils;
		this.questaoavaliacaos = questaoavaliacaos;
	}

	@Id

	@Column(name = "codPerfil", unique = true, nullable = false)
	public int getCodPerfil() {
		return this.codPerfil;
	}

	public void setCodPerfil(int codPerfil) {
		this.codPerfil = codPerfil;
	}

	@Column(name = "descricao", nullable = false, length = 20)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoperfil")
	public Set<Loginperfil> getLoginperfils() {
		return this.loginperfils;
	}

	public void setLoginperfils(Set<Loginperfil> loginperfils) {
		this.loginperfils = loginperfils;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoperfil")
	public Set<Questaoavaliacao> getQuestaoavaliacaos() {
		return this.questaoavaliacaos;
	}

	public void setQuestaoavaliacaos(Set<Questaoavaliacao> questaoavaliacaos) {
		this.questaoavaliacaos = questaoavaliacaos;
	}

}
