package br.pucsp.locar.entity;
// Generated 15/05/2016 13:10:26 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipoveiculo generated by hbm2java
 */
@Entity
@Table(name = "tipoveiculo", catalog = "schema_locar")
public class Tipoveiculo implements java.io.Serializable {

	private Integer codTipoVeiculo;
	private String descricao;
	private Set<Modeloveiculo> modeloveiculos = new HashSet<Modeloveiculo>(0);

	public Tipoveiculo() {
	}

	public Tipoveiculo(String descricao) {
		this.descricao = descricao;
	}

	public Tipoveiculo(String descricao, Set<Modeloveiculo> modeloveiculos) {
		this.descricao = descricao;
		this.modeloveiculos = modeloveiculos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "codTipoVeiculo", unique = true, nullable = false)
	public Integer getCodTipoVeiculo() {
		return this.codTipoVeiculo;
	}

	public void setCodTipoVeiculo(Integer codTipoVeiculo) {
		this.codTipoVeiculo = codTipoVeiculo;
	}

	@Column(name = "descricao", nullable = false, length = 30)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoveiculo")
	public Set<Modeloveiculo> getModeloveiculos() {
		return this.modeloveiculos;
	}

	public void setModeloveiculos(Set<Modeloveiculo> modeloveiculos) {
		this.modeloveiculos = modeloveiculos;
	}

}
