package br.pucsp.locar.entity;
// Generated 28/05/2016 00:02:55 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Avaliacao generated by hbm2java
 */
@Entity
@Table(name = "avaliacao", catalog = "schema_locar")
public class Avaliacao implements java.io.Serializable {

	private Integer idAvaliacao;
	private Questaoavaliacao questaoavaliacao;
	private BigDecimal nota;
	private String comentario;
	private Date dtinclusao;
	private Set<Avaliacaolocacao> avaliacaolocacaos = new HashSet<Avaliacaolocacao>(0);

	public Avaliacao() {
	}

	public Avaliacao(Questaoavaliacao questaoavaliacao, BigDecimal nota, Date dtinclusao) {
		this.questaoavaliacao = questaoavaliacao;
		this.nota = nota;
		this.dtinclusao = dtinclusao;
	}

	public Avaliacao(Questaoavaliacao questaoavaliacao, BigDecimal nota, String comentario, Date dtinclusao,
			Set<Avaliacaolocacao> avaliacaolocacaos) {
		this.questaoavaliacao = questaoavaliacao;
		this.nota = nota;
		this.comentario = comentario;
		this.dtinclusao = dtinclusao;
		this.avaliacaolocacaos = avaliacaolocacaos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idAvaliacao", unique = true, nullable = false)
	public Integer getIdAvaliacao() {
		return this.idAvaliacao;
	}

	public void setIdAvaliacao(Integer idAvaliacao) {
		this.idAvaliacao = idAvaliacao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idQuestao", nullable = false)
	public Questaoavaliacao getQuestaoavaliacao() {
		return this.questaoavaliacao;
	}

	public void setQuestaoavaliacao(Questaoavaliacao questaoavaliacao) {
		this.questaoavaliacao = questaoavaliacao;
	}

	@Column(name = "nota", nullable = false, precision = 2, scale = 1)
	public BigDecimal getNota() {
		return this.nota;
	}

	public void setNota(BigDecimal nota) {
		this.nota = nota;
	}

	@Column(name = "comentario", length = 100)
	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dtinclusao", nullable = false, length = 19)
	public Date getDtinclusao() {
		return this.dtinclusao;
	}

	public void setDtinclusao(Date dtinclusao) {
		this.dtinclusao = dtinclusao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "avaliacao")
	public Set<Avaliacaolocacao> getAvaliacaolocacaos() {
		return this.avaliacaolocacaos;
	}

	public void setAvaliacaolocacaos(Set<Avaliacaolocacao> avaliacaolocacaos) {
		this.avaliacaolocacaos = avaliacaolocacaos;
	}

}
