package br.pucsp.locar.entity;
// Generated 28/05/2016 00:02:55 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Montadoraveiculo generated by hbm2java
 */
@Entity
@Table(name = "montadoraveiculo", catalog = "schema_locar")
public class Montadoraveiculo implements java.io.Serializable {

	private Integer codMontadora;
	private String descricao;
	private Set<Modeloveiculo> modeloveiculos = new HashSet<Modeloveiculo>(0);

	public Montadoraveiculo() {
	}

	public Montadoraveiculo(String descricao) {
		this.descricao = descricao;
	}

	public Montadoraveiculo(String descricao, Set<Modeloveiculo> modeloveiculos) {
		this.descricao = descricao;
		this.modeloveiculos = modeloveiculos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "codMontadora", unique = true, nullable = false)
	public Integer getCodMontadora() {
		return this.codMontadora;
	}

	public void setCodMontadora(Integer codMontadora) {
		this.codMontadora = codMontadora;
	}

	@Column(name = "descricao", nullable = false, length = 30)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "montadoraveiculo")
	public Set<Modeloveiculo> getModeloveiculos() {
		return this.modeloveiculos;
	}

	public void setModeloveiculos(Set<Modeloveiculo> modeloveiculos) {
		this.modeloveiculos = modeloveiculos;
	}

}
