package br.pucsp.locar.entity;
// Generated 28/05/2016 00:02:55 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pagamento generated by hbm2java
 */
@Entity
@Table(name = "pagamento", catalog = "schema_locar")
public class Pagamento implements java.io.Serializable {

	private Integer idPagamento;
	private Login login;
	private long numerocartao;
	private String nometitular;
	private String validade;
	private Set<Locacao> locacaos = new HashSet<Locacao>(0);

	public Pagamento() {
	}

	public Pagamento(Login login, long numerocartao, String nometitular, String validade) {
		this.login = login;
		this.numerocartao = numerocartao;
		this.nometitular = nometitular;
		this.validade = validade;
	}

	public Pagamento(Login login, long numerocartao, String nometitular, String validade, Set<Locacao> locacaos) {
		this.login = login;
		this.numerocartao = numerocartao;
		this.nometitular = nometitular;
		this.validade = validade;
		this.locacaos = locacaos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idPagamento", unique = true, nullable = false)
	public Integer getIdPagamento() {
		return this.idPagamento;
	}

	public void setIdPagamento(Integer idPagamento) {
		this.idPagamento = idPagamento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idLogin", nullable = false)
	public Login getLogin() {
		return this.login;
	}

	public void setLogin(Login login) {
		this.login = login;
	}

	@Column(name = "numerocartao", nullable = false, precision = 16, scale = 0)
	public long getNumerocartao() {
		return this.numerocartao;
	}

	public void setNumerocartao(long numerocartao) {
		this.numerocartao = numerocartao;
	}

	@Column(name = "nometitular", nullable = false, length = 20)
	public String getNometitular() {
		return this.nometitular;
	}

	public void setNometitular(String nometitular) {
		this.nometitular = nometitular;
	}

	@Column(name = "validade", nullable = false, length = 5)
	public String getValidade() {
		return this.validade;
	}

	public void setValidade(String validade) {
		this.validade = validade;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pagamento")
	public Set<Locacao> getLocacaos() {
		return this.locacaos;
	}

	public void setLocacaos(Set<Locacao> locacaos) {
		this.locacaos = locacaos;
	}

}
