package br.pucsp.locar.entity;
// Generated 28/05/2016 00:02:55 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "schema_locar", uniqueConstraints = { @UniqueConstraint(columnNames = "cnh"),
		@UniqueConstraint(columnNames = "cpf"), @UniqueConstraint(columnNames = "email") })
public class Usuario implements java.io.Serializable {

	private String idLogin;
	private Endereco endereco;
	private Login login;
	private long cpf;
	private long cnh;
	private String email;
	private String nome;
	private Date dtNasc;
	private String rg;
	private String orgaoemissor;
	private Date dtinclusao;
	private Date dtalteracao;
	private char status;

	public Usuario() {
	}

	public Usuario(Endereco endereco, Login login, long cpf, long cnh, String email, String nome, Date dtNasc,
			String rg, String orgaoemissor, Date dtinclusao, char status) {
		this.endereco = endereco;
		this.login = login;
		this.cpf = cpf;
		this.cnh = cnh;
		this.email = email;
		this.nome = nome;
		this.dtNasc = dtNasc;
		this.rg = rg;
		this.orgaoemissor = orgaoemissor;
		this.dtinclusao = dtinclusao;
		this.status = status;
	}

	public Usuario(Endereco endereco, Login login, long cpf, long cnh, String email, String nome, Date dtNasc,
			String rg, String orgaoemissor, Date dtinclusao, Date dtalteracao, char status) {
		this.endereco = endereco;
		this.login = login;
		this.cpf = cpf;
		this.cnh = cnh;
		this.email = email;
		this.nome = nome;
		this.dtNasc = dtNasc;
		this.rg = rg;
		this.orgaoemissor = orgaoemissor;
		this.dtinclusao = dtinclusao;
		this.dtalteracao = dtalteracao;
		this.status = status;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "login"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "idLogin", unique = true, nullable = false, length = 15)
	public String getIdLogin() {
		return this.idLogin;
	}

	public void setIdLogin(String idLogin) {
		this.idLogin = idLogin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codEnd", nullable = false)
	public Endereco getEndereco() {
		return this.endereco;
	}

	public void setEndereco(Endereco endereco) {
		this.endereco = endereco;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Login getLogin() {
		return this.login;
	}

	public void setLogin(Login login) {
		this.login = login;
	}

	@Column(name = "cpf", unique = true, nullable = false, precision = 11, scale = 0)
	public long getCpf() {
		return this.cpf;
	}

	public void setCpf(long cpf) {
		this.cpf = cpf;
	}

	@Column(name = "cnh", unique = true, nullable = false, precision = 15, scale = 0)
	public long getCnh() {
		return this.cnh;
	}

	public void setCnh(long cnh) {
		this.cnh = cnh;
	}

	@Column(name = "email", unique = true, nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "nome", nullable = false, length = 100)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dtNasc", nullable = false, length = 10)
	public Date getDtNasc() {
		return this.dtNasc;
	}

	public void setDtNasc(Date dtNasc) {
		this.dtNasc = dtNasc;
	}

	@Column(name = "rg", nullable = false, length = 10)
	public String getRg() {
		return this.rg;
	}

	public void setRg(String rg) {
		this.rg = rg;
	}

	@Column(name = "orgaoemissor", nullable = false, length = 5)
	public String getOrgaoemissor() {
		return this.orgaoemissor;
	}

	public void setOrgaoemissor(String orgaoemissor) {
		this.orgaoemissor = orgaoemissor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dtinclusao", nullable = false, length = 19)
	public Date getDtinclusao() {
		return this.dtinclusao;
	}

	public void setDtinclusao(Date dtinclusao) {
		this.dtinclusao = dtinclusao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dtalteracao", length = 19)
	public Date getDtalteracao() {
		return this.dtalteracao;
	}

	public void setDtalteracao(Date dtalteracao) {
		this.dtalteracao = dtalteracao;
	}

	@Column(name = "status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

}
